services:
  borg:
    image: git.jrdn.dev/jordanwalster/borgbackup:latest
    ports:
      - 22:22
    volumes:
      - ./borg:/opt/borg
    environment:
      - SSH_PASSWORD=value
    restart: always
