services:
  borg:
    image: ghcr.io/jordanwalster/borgbackup:latest
    ports:
      - 22:22
    volumes:
      - ./borg:/opt/borg
      - ssh-keys:/home/borg/.ssh
    environment:
      - SSH_PASSWORD=value
    restart: always

volumes:
  ssh-keys:
